Update Node to 12.14.0 and NPM to 6.13.4, add @silvermine/standardization
silvermine/s3-utils pull request #6
Opened 2020-11-20 18:49 UTC by pbredenberg

2020-11-20 20:32 UTC, pbredenberg commented
@jthomerson ready for you

2020-11-26 19:56 UTC, jthomerson requested changes
Just the one question

2020-11-26 19:56 UTC, jthomerson commented on .editorconfig
> +[*]
@pbredenberg aren't we usually making this a symlink to the file in the standardization repo (i.e. `node_modules/@silvermine/standardization/.editorconfig`) so that it's not duplicated everywhere?

2020-11-26 19:58 UTC, pbredenberg commented on .editorconfig
> +[*]
It hadn't occurred to me to do that. We certainly could if you want. The only reason why I personally wouldn't is if there was something specific I wanted to override in the project.

2020-11-26 20:03 UTC, jthomerson commented on .editorconfig
> +[*]
Ah, I see. I guess we did it on some internal projects when we were pointing at the eslint config. Let's go ahead and do it on all these since it gives us one place to keep the editorconfig file updated.

2020-11-27 13:27 UTC, pbredenberg commented on .editorconfig
> +[*]
did it! @jthomerson back to you

2020-11-27 13:40 UTC, jthomerson approved these changes

2020-11-27 13:40 UTC, merged